# Generated by Django 4.2.1 on 2023-05-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='poll_id',
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
