# Generated by Django 4.2.1 on 2023-05-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_remove_poll_poll_id_alter_poll_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='objectsave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=30)),
            ],
        ),
    ]
